language: node_js
node_js:
- node
- 10
- 8
after_success:
- npm run coverage
- npm run build
deploy:
  provider: npm
  email: "$NPM_EMAIL"
  api_key:
    secure: YcXtnE+ToSD0qKutAXpaECwb7G+6vH2S5bPNOhNUGKtHwGd5qqBf+ETPzsHcy93nthWNNB+2Cl0hDwyAqEM2yvtbd4QJ/4i7qw/id0nqR2oB6jIujImB8Yb08DfnV3i9bBMuQJ9GlUHoXbfeW4cNagHM85Ku2JvunuillvOz8SczkKONLFCjoSDHTj9LN6LpBxrPWL76yjNDQXZBBr8j7UAeaE5L3zLDumMlrBfFUYqbaRJ5yCiEChfFsxYoBrRtsLoOiJCfdno5kblou4wLTF3j0rLOB/JC0Ojgc/W0kjZCRVu9GbgFBH3EVIBbUK7QesMIaY13ETrofuk5paPVY/RfD0YRz1SF8CoW0oRfijPCUng6fB5pD1lx3lPjFbKRrrSxCYqYFWJ5TjWom+FwJnaVUNUHyYQRgKBT9r/8hHgH1daboHRiITO9Q1hpLlHnA4qHhxJFrYZ12oGTaaRtrLoIyswlcOHCjsQ+BR3uZEncC5NpYIyXLdinu0P82A7Hu8ZacmKA5wj9qz/KYxkoipd+IZvt2sZdV3aOcb94xlWoZ3hfGbopZq3BgfqcsrjgVgPkKSTl5aKFuH9qsmgNz70mo1mnD5Y47GyhPq+YJsJwG7vB7KhaZpH8hwzuhcRQTe2RUmKW7fjcJmm+rg2ZwL34+6ZWqGCzt+UdMjgrkKI=                 
  on:
    tags: true
    repo: up9cloud/graphql-tools-type-email
    branch: master
